# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    tags: ['*']
  schedule:
    - cron:  '0 12 * * 3'
    
name: rostemplate-gh-pages

jobs:
  rostemplate-gh-pages:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache-version: 900
          extra-packages: |
            pkgdown
            remotes
            devtools
            ropenspain/rostemplate
            mapSpain
            classInt
            raster
            sp
            gstat
            geoR
            scatterplot3d
            styler
            geofacet
            reactable
            leaflet
            tidyverse
            gifski
          needs: website

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'