# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    tags: ['*']
  schedule:
    - cron:  '0 12 * * 3'

name: rostemplate-gh-pages

jobs:
  rostemplate-gh-pages:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true


      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::cli
            any::rcmdcheck
            any::pkgdown
            any::mapSpain
            any::classInt
            any::stars
            any::gganimate
            any::raster
            any::sp
            any::gstat
            any::scatterplot3d
            any::styler
            any::geofacet
            any::reactable
            any::leaflet
            any::tidyverse
            any::gifski
            any::geoR
            ropenspain/rostemplate
          needs: website

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, run_dont_run = TRUE)'
